version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
    delete:
        enabled: true
http:
    addr: :5000
notifications:
    endpoints:
        - name: alistener
          url: http://159.65.238.188:5005/check_image
          headers:
            Authorization: [Bearer ]
          timeout: 500000ms
          threshold: 5
          backoff: 1s
