version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
notifications:
    endpoints:
        - name: alistener
          url: http://localhost:5001/check_image
          headers:
            Authorization: [Bearer ]
          timeout: 500ms
          threshold: 5
          backoff: 1s