version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
notifications:
    endpoints:
        - name: alistener
          url: http://172.17.0.1:9999/check_image
          timeout: 5000ms
          threshold: 5
          backoff: 10s